parameters:
  os: linux
  pythonVersions: [2.7, 3.7, 3.6, 3.5]

jobs:
  - job: test
    pool:
      ${{ if eq(parameters.os, 'linux') }}:
        vmImage: ubuntu-latest
      ${{ if eq(parameters.os, 'windows') }}:
        vmImage: windows-2019

    strategy:
      matrix:
        ${{ each version in parameters.pythonVersions }}:
          "py${{ version }}":
            os: ${{ parameters.os }}
            python.version: ${{ version }}

    steps:

      - bash: |
          py=$(echo $(python.version) | sed "s/\.//")
          echo "##vso[task.setvariable variable=PY]$py"

      - task: UsePythonVersion@0
        displayName: Configure Python
        inputs:
          versionSpec: '$(python.version)'

      - bash: |
            set -euxo pipefail
            sudo apt-get update
            #sudo apt-get install -y gcc python3-dev libselinux1 lxc lxc-dev lxd lxd-client
            pip install tox
            python -m pip install tox -U
        displayName: Install tox

      - bash: tox -e py$(PY)
        displayName: Run tox
        env:
          PYTEST_OPTIONS: -s
