---
# Until bug below is sorted we will not allow dependabot to run by itself
# https://github.com/dependabot/dependabot-core/issues/369
version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    labels:
      - dependabot-deps-updates
      - skip-changelog
    versioning-strategy: lockfile-only
    open-pull-requests-limit: 0 # neutered
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "skip-changelog"
