jobs:
  - job: 'pretest'
    pool:
      vmImage: 'ubuntu-latest'
    steps:

      - task: DockerInstaller@0
        displayName: Docker Installer

      - task: UsePythonVersion@0
        displayName: 'Use Python $(python.version)'
        inputs:
          versionSpec: '3.7'

      - bash: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y gcc python3-dev libselinux1 docker
          pip install tox
        displayName: 'Install test dependencies'

      - script: tox -e lint
        displayName: 'lint'

      - script: tox -e devel
        displayName: 'devel'

      - script: tox -e distros
        displayName: 'distros'

  - template: .azure-pipelines/jobs/test.yml
