# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

# Required by RHEL8 image which defaults to non root
USER root

CMD ["sh", "-c", "while true; do sleep 10000; done"]
